# Generated by Django 2.1 on 2020-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
